import { AgentActivity, InboundOpportunity, PipelineStage, Supplier } from "@/interfaces/supplier";

export const suppliersData: Supplier[] = [
    {
        id: "1",
        name: "Journey Foods Test",
        location: "Austin, TX",
        score: 72.73,
        status: "Pending",
        lastUpdated: "Mar 20, 2026",
        ingredients: ["Blueberry", "Papaya", "hibiscus flow", "Mango", "Acai", "Spirulina", "Chlorella", "Matcha"],
        phone: null,
        email: "contact@journeyfoods.com",
        website: "journeyfoods.com",
        certifications: ["USDA Organic", "Non-GMO"],
        description: "A leading supplier of organic superfoods and functional ingredients.",
        pipelineStage: "email-sent",
        agentStats: { emails: 2, quotes: 1, pending: 1, invited: false },
        dataSource: "sap"
    },
    {
        id: "2",
        name: "check12345",
        location: "Unknown Location",
        score: 90,
        status: "Pending",
        lastUpdated: "Mar 18, 2026",
        ingredients: [],
        phone: null,
        email: "check@example.com",
        website: null,
        certifications: [],
        description: "New supplier pending verification.",
        pipelineStage: "ingredient-need",
        agentStats: { emails: 0, quotes: 0, pending: 0, invited: false },
        dataSource: "manual"
    },
    {
        id: "3",
        name: "abhi34",
        location: "Unknown Location",
        score: 90,
        status: "Pending",
        lastUpdated: "Mar 17, 2026",
        ingredients: [],
        phone: null,
        email: "abhi@example.com",
        website: null,
        certifications: [],
        description: "New supplier pending verification.",
        pipelineStage: "supplier-match",
        agentStats: { emails: 0, quotes: 0, pending: 1, invited: false },
        dataSource: "excel"
    },
    {
        id: "4",
        name: "LinkOne Ingredient Solutions",
        location: "Springfield, MO",
        score: 24.24,
        status: "Pending",
        lastUpdated: "Mar 16, 2026",
        ingredients: ["Oils", "Eggs", "Nuts", "Seeds", "Dairy"],
        phone: "+1 417-236-9602",
        email: "info@linkone.com",
        website: "linkone.com",
        certifications: ["FDA Approved", "GFSI"],
        description: "Comprehensive ingredient solutions for food manufacturers.",
        pipelineStage: "quote-requested",
        agentStats: { emails: 1, quotes: 1, pending: 1, invited: false },
        dataSource: "sap"
    },
    {
        id: "5",
        name: "Pharmore Ingredients Inc",
        location: "Salt Lake City, UT",
        score: 90,
        status: "Pending",
        lastUpdated: "Mar 15, 2026",
        ingredients: ["Chondroitin Sulfate Sodium", "Glucosamine HCl"],
        phone: "+1 801-446-8188",
        email: "sales@pharmore.com",
        website: "pharmore.com",
        certifications: ["GMP Certified", "NSF"],
        description: "Specialty ingredients for nutraceuticals and dietary supplements.",
        pipelineStage: "platform-invite",
        agentStats: { emails: 3, quotes: 2, pending: 0, invited: true },
        dataSource: "oracle"
    },
    {
        id: "6",
        name: "HPS Food & Ingredients Inc.",
        location: "Boulder, CO",
        score: 90,
        status: "Connected",
        lastUpdated: "Mar 15, 2026",
        ingredients: ["Hulled Hempseeds", "Roasted Whole Hempseed", "Cold Pressed Hempseed Oil"],
        phone: "+1 844-436-7477",
        email: "info@hpsfoods.com",
        website: "hpsfoods.com",
        certifications: ["Organic", "Kosher", "Halal"],
        description: "Premium hemp-based ingredients for food and beverage applications.",
        pipelineStage: "connected",
        agentStats: { emails: 5, quotes: 3, pending: 0, invited: true },
        dataSource: "sap"
    },
]

export const inboundOpportunities: InboundOpportunity[] = [
    {
        id: "1",
        brandName: "GreenVita Foods",
        ingredient: "Organic Mango Puree",
        quantity: "2,000 kg/month",
        timeline: "Q2 2026",
        status: "new",
        receivedAt: "2 hours ago",
    },
    {
        id: "2",
        brandName: "NutriBlend Co",
        ingredient: "Pea Protein Isolate",
        quantity: "5,000 kg/month",
        timeline: "Ongoing",
        status: "reviewing",
        receivedAt: "1 day ago",
    },
    {
        id: "3",
        brandName: "CleanLabel Snacks",
        ingredient: "Turmeric Extract",
        quantity: "500 kg/quarter",
        timeline: "Q3 2026",
        status: "responded",
        receivedAt: "3 days ago",
    },
]

export const agentActivities: AgentActivity[] = [
    {
        id: "1",
        type: "ingredient-need",
        title: "Ingredient need detected: Blueberry Powder",
        description: "Agent identified a gap in the product formulation for organic blueberry powder based on current product pipeline requirements.",
        timestamp: "Jan 15, 10:23 AM",
        details: "The AI agent analyzed your upcoming Q2 product launches and found that 3 new SKUs require organic blueberry powder. Current supplier inventory shows limited availability. Recommended action: Connect with suppliers who can fulfill 500kg+ orders.",
    },
    {
        id: "2",
        type: "ingredient-need",
        title: "Ingredient need detected: Spirulina",
        description: "Superfood blend requires high quality spirulina powder for the wellness line expansion.",
        timestamp: "Jan 15, 10:24 AM",
        details: "Based on your product development roadmap, spirulina is needed for 2 new superfood blend SKUs launching in Q3.",
    },
    {
        id: "3",
        type: "supplier-match",
        title: "Supplier match found: HPS Foods",
        description: "High compatibility score (92%) for hemp protein requirements.",
        timestamp: "Jan 14, 3:45 PM",
        details: "HPS Foods has been identified as a strong match based on: certifications (Organic, Kosher), pricing competitiveness, lead time reliability, and ingredient quality scores.",
    },
    {
        id: "4",
        type: "email-sent",
        title: "Outreach email sent to Pharmore",
        description: "Initial partnership inquiry sent. Tracking enabled.",
        timestamp: "Jan 14, 2:30 PM",
    },
    {
        id: "5",
        type: "quote-response",
        title: "Quote received from LinkOne",
        description: "Competitive pricing received for bulk oils order.",
        timestamp: "Jan 13, 11:15 AM",
    },
]
export const pipelineStages: { key: PipelineStage; label: string }[] = [
    { key: "ingredient-need", label: "Ingredient\nNeed" },
    { key: "supplier-match", label: "Supplier\nMatch" },
    { key: "email-sent", label: "Email Sent" },
    { key: "quote-requested", label: "Quote\nRequested" },
    { key: "platform-invite", label: "Platform\nInvite" },
    { key: "connected", label: "Connected" },
]