export const routes = {
  AUTH: "/auth",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RECOVERY_PASSWORD: "/auth/recovery-password",
  APP_HOME: "/overview",
  APP_OVERVIEW: "/overview",
  APP_GENERATE: "/generate",
  APP_WORKFLOWS: "/workflows",
  APP_INGREDIENTS: "/ingredients",
  APP_PRODUCTS: "/products",
  APP_SUPPLIERS: "/suppliers",
  APP_PACKAGING: "/packaging",
  APP_ANALYTICS: "/analytics",
  APP_INTEGRATIONS: "/integrations",
  APP_GUAVA: "/guava",
} as const;
