export const AUTH_STRINGS = {
  login: {
    title: "Login",
    submit: "Login",
    submitLoading: "Logging in...",
    forgotPassword: "Forgot password?",
    needAccount: "Need an account?",
    createAccount: "Create account",
    errorFallback: "Login failed",
  },
  register: {
    title: "Create Account",
    submit: "Register",
    submitLoading: "Creating account...",
    hasAccount: "Already have an account?",
    login: "Login",
    successTitle: "Registration completed successfully!",
    successBodyPrefix: "Please check",
    successBodySuffix: "to verify your account. Once verified, come back and login.",
    errorFallback: "Registration failed",
  },
  forgotPassword: {
    title: "Forgot your password?",
    subtitle: "We will send reset instructions to your email.",
    submit: "Send me instructions",
    submitLoading: "Sending...",
    backToLogin: "Back to login",
    errorFallback: "Failed to send instructions",
  },
  recoveryPassword: {
    title: "Reset Password",
    submit: "Change password",
    submitLoading: "Saving...",
    backToLogin: "Back to login",
    invalidLink: "Invalid or expired reset link",
    errorFallback: "Password reset failed",
  },
} as const;
